In [2]:
!pip install -Uqqq pip --progress-bar off
!pip install -qqq sentence-transformers==2.2.2 --progress-bar off

  Preparing metadata (setup.py) ... done


In [3]:
from sentence_transformers import SentenceTransformer, util

In [4]:
sentence_1 = "Bitcoin is up 34% since Bank of England Governor said 'Be prepared to lose all your money in BTC and crypto.'"
sentence_2 = "One of the biggest bull traps I've ever seen"

In [5]:
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


.gitattributes:   0%|          | 0.00/1.23k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [6]:
model.max_seq_length

384

In [7]:
corpus=[
    "Bitcoin is up 34% since Bank of England Governor said 'Be prepared to lose all your money in BTC and crypto.'",
    "One of the biggest bull traps I've ever seen.",
    "How I sleep knowing ethereum is going to 10k in 2025.",
    "Bitcoin is a scam.",
    "Is The $BTC BOTTOM In? Are you team BULL or team BEAR? Do you have data to prove your point?",
    "I will stop bragging about calling the top when I start bragging about calling the bottom. #bitcoin",
    "First powerlifting meet of year and a new squat PR!!",
    "On January 9th, 2023, the American Academy of Pediatrics published new guidlines treating obesity in children adolescents.",
    "What's worse, someone dropping the bar from the top of deadlift or not putting their shopping cart away?",
    "The sport of powerlifting includes squart bench and deadlift. But the concept of powerlifting is Force = Mass x Acceleration."
]

In [8]:
corpus_embeddings = model.encode(corpus,show_progress_bar=True, convert_to_tensor=True)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
corpus_embeddings.shape

torch.Size([10, 768])

In [10]:
corpus_embeddings[0]

tensor([-5.3459e-02, -1.5844e-02, -3.1743e-02,  2.7226e-02,  3.1214e-02,
         2.8494e-02, -7.2695e-02, -1.2775e-02, -2.9571e-02,  8.2445e-03,
        -1.5555e-02,  9.0650e-02, -4.7734e-02,  8.2903e-02,  2.9071e-02,
        -2.1475e-02,  1.0546e-02,  4.7358e-03,  3.6490e-03, -3.3507e-02,
         1.4732e-04, -2.1216e-02, -1.0329e-03, -4.6333e-02,  2.2451e-02,
        -2.0459e-02,  4.1381e-02,  4.8300e-02,  1.0083e-02, -3.3709e-02,
         1.2931e-02, -9.3284e-02, -5.7206e-02,  2.2041e-02,  1.9408e-06,
        -5.2757e-02, -6.7647e-03,  3.2817e-02, -3.5538e-02, -5.8601e-02,
        -3.8737e-02, -7.1928e-02, -1.9254e-02, -1.5066e-02, -5.3809e-02,
         2.1386e-02,  1.7038e-02,  1.0725e-02, -5.0797e-02,  5.0363e-02,
        -1.3882e-02,  4.8990e-03,  4.8315e-02,  1.2081e-02, -4.4652e-02,
        -1.8506e-02,  1.5896e-02,  6.7113e-02,  1.6710e-02,  5.3049e-02,
        -3.6113e-02,  5.5248e-02, -1.3574e-03, -2.3665e-04, -1.9322e-02,
         4.5760e-03,  6.4266e-02,  3.4534e-02, -2.0

In [11]:
query = "How high will bitcoin go?"

In [12]:
query_embeddidng = model.encode(query,convert_to_tensor=True)

In [13]:
query_embeddidng

tensor([-1.6440e-02,  3.2738e-02, -3.3854e-02,  2.5782e-03,  4.6909e-02,
        -1.0622e-02, -4.9374e-02, -2.5929e-02,  4.1010e-02, -3.7868e-03,
         8.4013e-03,  4.4253e-03, -3.8478e-02,  1.1281e-01,  6.4805e-03,
        -4.7081e-02,  4.1241e-02, -2.2989e-02,  1.0063e-02, -4.0439e-02,
        -1.6192e-02, -5.6703e-02,  4.1887e-02, -2.9924e-03, -2.0055e-02,
         9.2723e-03,  2.3443e-02,  4.1819e-02, -3.8099e-02, -5.1336e-03,
        -7.1172e-02, -2.7961e-02, -4.7446e-02,  5.1631e-02,  1.4831e-06,
        -4.5730e-02,  6.1660e-04,  3.3853e-02, -1.7810e-02, -8.5618e-02,
        -8.5605e-02, -2.6440e-02, -9.6930e-03,  1.9836e-02, -1.2204e-02,
         2.4640e-02, -4.3704e-02,  2.7261e-02, -2.3189e-02,  2.2393e-02,
        -2.7534e-03, -6.5008e-02,  5.6481e-02,  9.2656e-03,  2.6180e-02,
        -4.4296e-02,  1.7331e-02,  5.5997e-02, -7.0871e-03,  3.7933e-02,
         2.9549e-03,  2.5222e-02,  1.5936e-02, -5.9648e-04,  1.3558e-02,
         2.8841e-02,  1.6692e-02,  3.8148e-02, -3.1

In [14]:
# since our query is very similary to first one so it give good result
util.cos_sim(query_embeddidng,corpus_embeddings[0])

tensor([[0.4987]])

In [15]:
# since our query not similar to last one in corpus so it gives -ve result
util.cos_sim(query_embeddidng,corpus_embeddings[9])

tensor([[-0.0160]])

In [16]:
sentence1_embedding = model.encode(sentence_1,convert_to_tensor=True)
sentence2_embedding = model.encode(sentence_2,convert_to_tensor=True)

In [17]:
util.cos_sim(sentence1_embedding,sentence2_embedding)

tensor([[0.1457]])

In [18]:
result = util.semantic_search(query_embeddidng,corpus_embeddings)
result

[[{'corpus_id': 2, 'score': 0.5171555280685425},
  {'corpus_id': 0, 'score': 0.4987412393093109},
  {'corpus_id': 4, 'score': 0.3828953802585602},
  {'corpus_id': 5, 'score': 0.3790990114212036},
  {'corpus_id': 3, 'score': 0.33788731694221497},
  {'corpus_id': 1, 'score': 0.09365622699260712},
  {'corpus_id': 6, 'score': 0.0900406464934349},
  {'corpus_id': 7, 'score': 0.04751607030630112},
  {'corpus_id': 8, 'score': 0.02535879984498024},
  {'corpus_id': 9, 'score': -0.01599607802927494}]]

In [19]:
# Train your own model


from sentence_transformers import SentencesDataset, InputExample, losses
from torch.utils.data import DataLoader

In [25]:
dataset = SentencesDataset([
    InputExample(
        texts = [
            "Bitcoin is up 34% since Bank of England Governor said 'Be prepared to lose all your money in BTC and crypto.'",
            "One of the biggest bull traps I've ever seen"
        ],label = 0.9
    )
],model)

In [26]:
dataloader = DataLoader(dataset, shuffle = True)
loss = losses.CosineSimilarityLoss(model=model)

In [27]:
save_path = "trained_model"

In [28]:
model.fit(train_objectives=[(dataloader,loss)], epochs=10,warmup_steps=10, output_path=save_path)

Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

Iteration:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
trained_model = SentenceTransformer(save_path)

In [31]:
sentence1_embedding = trained_model.encode(sentence_1,convert_to_tensor=True)
sentence2_embedding = trained_model.encode(sentence_2,convert_to_tensor=True)

In [32]:
util.cos_sim(sentence1_embedding,sentence2_embedding)

tensor([[0.8182]])